DeliveryReactiveLicensing/Controllers/ClientController.cs
using System;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using DeliveryReactiveLicensing.Resources;
using Infrastructure.JqGrid.Model;
using Infrastructure.Models;
using Licensing.Model.Management;
using Licensing.Repository.Catalog;
using Licensing.Repository.Database;
using Licensing.Repository.Database.Metadata;
using Licensing.Repository.Log;
using Licensing.Repository.Management;
using Licensing.Repository.Shared;
using Microsoft.AspNet.Identity;

namespace DeliveryReactiveLicensing.Controllers
{
    [Authorize]
    public class ClientController : Controller
    {
        // GET: Default

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(JqGridFilterModel opts)
        {
            using (var repository = new GenericRepository<ViewClientGrid>())
            {
                var result = repository.JqGridFindBy(opts, ViewClientGridJson.Key, ViewClientGridJson.Columns, null
                    , ViewClientGridJson.DynamicToDto);
                return Json(result);
            }
        }


        [HttpPost]
        public ActionResult Upsert(int? id)
        {
            ClientModel model = null;
            try
            {
                using (var repositoryCatalog = new CountryRepository())
                {
                    if (id.HasValue)
                    {
                        var repository = new ClientRepository(repositoryCatalog.DbConn);
                        model = repository.FindViewById(id.Value);
                    }
                    else
                    {
                        model = new ClientModel
                        {
                            ClientId = EntityConstants.NULL_VALUE
                        };
                    }

                    ViewBag.CatCountry = new JavaScriptSerializer().Serialize(repositoryCatalog.FindAll());
                }
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, id);
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DoUpsert(ClientModel model)
        {
            try
            {
                if (ModelState.IsValid == false)
                {
                    return Json(new ResponseMessageModel
                    {
                        HasError = true,
                        Title = ResShared.TITLE_REGISTER_FAILED,
                        Message = ResShared.ERROR_INVALID_MODEL
                    });
                }


                using (var repository = new GenericRepository<Client>())
                {
                    if (model.ClientId == EntityConstants.NULL_VALUE)
                    {
                        var inModel = model.ToDataModel();
                        //inModel.ActivationCode = Convert.ToBase64String(Encoding.UTF8.GetBytes(Guid.NewGuid().ToString()));
                        inModel.InsDateTime = DateTime.Now;
                        inModel.InsUserId = User.Identity.GetUserId();
                        repository.Add(inModel);
                    }
                    else
                    {
                        var oldModel = repository.FindById(model.ClientId);
                        var inModel = model.UpdateModel(oldModel, User.Identity.GetUserId());

                        repository.Update(inModel);
                    }

                    return Json(new ResponseMessageModel
                    {
                        HasError = false,
                        Title = ResShared.TITLE_REGISTER_SUCCESS,
                        Message = ResShared.INFO_REGISTER_SAVED
                    });
                }

            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, model.ClientId, model.FirstName, model.LastName);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Title = ResShared.TITLE_REGISTER_FAILED,
                    Message = ResShared.ERROR_UNKOWN
                });
            }
        }

        [HttpPost]
        public ActionResult DoObsolete(int id)
        {
            try
            {
                using (var repository = new GenericRepository<License>())
                {
                    var model = repository.FindById(id);
                    if (model == null)
                    {
                        return Json(new ResponseMessageModel
                        {
                            HasError = true,
                            Title = ResShared.TITLE_OBSOLETE_FAILED,
                            Message = ResShared.ERROR_MODEL_NOTFOUND
                        });
                    }

                    model.IsObsolete = true;
                    repository.Update(model);

                    return Json(new ResponseMessageModel
                    {
                        HasError = false,
                        Title = ResShared.TITLE_OBSOLETE_SUCCESS,
                        Message = ResShared.INFO_REGISTER_SAVED
                    });
                }
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, id);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Title = ResShared.TITLE_OBSOLETE_FAILED,
                    Message = ResShared.ERROR_UNKOWN
                });
            }
        }
    }
}

DeliveryReactiveLicensing/Controllers/LicenseController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using DeliveryReactiveLicensing.Resources;
using DeliveryReactiveLicensing.Service.License;
using Infrastructure.JqGrid.Model;
using Infrastructure.Models;
using Licensing.Model.Management;
using Licensing.Repository.Catalog;
using Licensing.Repository.Database;
using Licensing.Repository.Database.Metadata;
using Licensing.Repository.Log;
using Licensing.Repository.Management;
using Licensing.Repository.Shared;
using Microsoft.AspNet.Identity;

namespace DeliveryReactiveLicensing.Controllers
{
    [Authorize]
    public class LicenseController : Controller
    {
        // GET: Default

        readonly ILicenseService _licenseService = new LicenseService();

        public ActionResult Index(int clId)
        {
            using (var repositoryClient = new ClientRepository())
            {
                var infoClient = repositoryClient.GetClientInfoById(clId);
                ViewBag.ClientInfo = infoClient;
                ViewBag.ClId = clId;
            }
            return View();
        }

        public ActionResult List(JqGridFilterModel opts, int clId)
        {
            using (var repository = new GenericRepository<ViewLicenseGrid>())
            {
                var result = repository.JqGridFindBy(opts, ViewLicenseGridJson.Key, ViewLicenseGridJson.Columns, 
                    (e => e.IsObsolete == false && e.ClientId == clId)
                    , ViewLicenseGridJson.DynamicToDto);
                return Json(result);
            }
        }


        [HttpPost]
        public ActionResult Upsert(int? id, int clId)
        {
            LicenseModel model = null;
            try
            {
                using (var repositoryClient = new ClientRepository())
                {
                    var infoClient = repositoryClient.GetClientInfoById(clId);
                    ViewBag.ClientInfo = infoClient;

                    if (id.HasValue)
                    {
                        var repository = new LicenseRepository(repositoryClient.DbConn);
                        model = repository.FindViewById(id.Value);
                    }
                    else
                    {
                        model = new LicenseModel
                        {
                            ClientId = clId,
                            IsActive = true,
                            LicenseId = EntityConstants.NULL_VALUE
                        };
                    }
                }
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, id);
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DoUpsert(LicenseModel model)
        {
            try
            {
                if (ModelState.IsValid == false)
                {
                    return Json(new ResponseMessageModel
                    {
                        HasError = true,
                        Title = ResShared.TITLE_REGISTER_FAILED,
                        Message = ResShared.ERROR_INVALID_MODEL
                    });
                }


                using (var repository = new GenericRepository<License>())
                {
                    if (model.LicenseId == EntityConstants.NULL_VALUE)
                    {
                        var inModel = model.ToDataModel();
                        inModel.ActivationCode = Convert.ToBase64String(Encoding.UTF8.GetBytes(Guid.NewGuid().ToString()));
                        inModel.InsDateTime = DateTime.Now;
                        inModel.InsUserId = User.Identity.GetUserId();
                        repository.Add(inModel);
                    }
                    else
                    {
                        var oldModel = repository.FindById(model.LicenseId);
                        var inModel = model.UpdateModel(oldModel, User.Identity.GetUserId());

                        repository.Update(inModel);
                    }

                    return Json(new ResponseMessageModel
                    {
                        HasError = false,
                        Title = ResShared.TITLE_REGISTER_SUCCESS,
                        Message = ResShared.INFO_REGISTER_SAVED
                    });
                }

            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, model.LicenseId, model.ClientId, model.Name);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Title = ResShared.TITLE_REGISTER_FAILED,
                    Message = ResShared.ERROR_UNKOWN
                });
            }
        }

        [HttpGet]
        public ActionResult DownloadCode(int id)
        {
            try
            {
                var message = _licenseService.GetInfoForActivationCode(id);
                var ms = new MemoryStream(Encoding.UTF8.GetBytes(message[0].Replace("<br/>", string.Empty)));
                return File(ms, "text/plain", message[1]);

            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, id);
                //
            }

            return Json("Archivo de activación incorrecto", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DoPayment(int id)
        {
            try
            {
                using (var repository = new GenericRepository<LicensePeriod>())
                {
                    var model = repository.FindById(id);
                    if (model == null)
                    {
                        return Json(new ResponseMessageModel
                        {
                            HasError = true,
                            Title = "Confirmación del pago",
                            Message = "No se encontró el registro para confirmar el pago. <br/> Por favor actualice la información e intente de nuevo la operación."
                        });
                    }

                    model.IsPayed = true;
                    repository.Update(model);

                    return Json(new ResponseMessageModel
                    {
                        HasError = false,
                        Title = ResShared.TITLE_OBSOLETE_SUCCESS,
                        Message = ResShared.INFO_REGISTER_SAVED
                    });
                }
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, id);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Title = ResShared.TITLE_OBSOLETE_FAILED,
                    Message = ResShared.ERROR_UNKOWN
                });
            }
        }

        
        [HttpPost]
        public ActionResult DoObsolete(int id)
        {
            try
            {
                using (var repository = new GenericRepository<License>())
                {
                    var model = repository.FindById(id);
                    if (model == null)
                    {
                        return Json(new ResponseMessageModel
                        {
                            HasError = true,
                            Title = ResShared.TITLE_OBSOLETE_FAILED,
                            Message = ResShared.ERROR_MODEL_NOTFOUND
                        });
                    }

                    model.IsObsolete = true;
                    repository.Update(model);

                    return Json(new ResponseMessageModel
                    {
                        HasError = false,
                        Title = ResShared.TITLE_OBSOLETE_SUCCESS,
                        Message = ResShared.INFO_REGISTER_SAVED
                    });
                }
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, id);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Title = ResShared.TITLE_OBSOLETE_FAILED,
                    Message = ResShared.ERROR_UNKOWN
                });
            }
        }


        [HttpPost]
        public async Task<ActionResult> SendEmail(int id)
        {
            try
            {
                var message = _licenseService.GetInfoForActivationCode(id);

                if (message == null || message.Length != 4 || String.IsNullOrEmpty(message[3]))
                {
                    return Json(new ResponseMessageModel
                    {
                        HasError = true,
                        Title = ResShared.TITLE_LICENCE,
                        Message = "No fue posible enviar el correo electrónico, revise que el proveedor esté activo o que el correo electrónico del destinatario sea correcto"
                    });
                }

                await new EmailService().SendAsync(new IdentityMessage
                {
                    Destination = message[3],
                    Subject = "Código para la activación del sistema Advanced Delivery Management",
                    Body = _licenseService.GenerateBody(message)
                });

                return Json(new ResponseMessageModel
                {
                    HasError = false,
                    Title = ResShared.TITLE_LICENCE,
                    Message = "El correo electrónico ha sido enviado de forma exitosa"
                });
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, id);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Title = ResShared.TITLE_OBSOLETE_FAILED,
                    Message = ResShared.ERROR_UNKOWN

DeliveryReactiveLicensing/Views/Client/Index.cshtml
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-xs-10">
        <h2>Módulo de licencias</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Inicio</a>
            </li>
            <li>
                Licencias
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content  animated fadeInRight" id="angJsjqGridId" ng-controller="modalDlgController">
    <div class="row">
        <div class="col-xs-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Listado de clientes</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="jqGrid_wrapper">
                        <table id="GridId"></table>
                        <div id="GridPager"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="blocker" ng-show="working">
        <div>
            Procesando...<img src="~/Content/img/ajax_loader.gif" alt="" />
        </div>
    </div>
</div>

@section css{
    <link href="~/Content/plugins/jQueryUI/jquery-ui-1.10.4.custom.min.css" rel="stylesheet" />
    <link href="~/Content/plugins/jqGrid/ui.jqgrid.css" rel="stylesheet" />
    <link href="~/Content/plugins/datapicker/datepicker3.css" rel="stylesheet" />
    <link href="~/Content/plugins/chosen/chosen.css" rel="stylesheet" />
    <link href="~/Content/plugins/iCheck/custom.css" rel="stylesheet">
}

@section scripts{

    <script src="~/Scripts/js/plugins/jqGrid/i18n/grid.locale-es.js"></script>
    <script src="~/Scripts/js/plugins/jqGrid/jquery.jqGrid.min.js"></script>
    <script src="~/Scripts/app/shared/upsertCtrl.js"></script>
    <script src="~/Scripts/app/shared/modalDlgCtrl.js"></script>
    <script src="~/Scripts/app/shared/hiddenDrct.js"></script>
    <script src="~/Scripts/app/ctrl/clientCtrl.js"></script>
    <script src="~/Scripts/js/plugins/datapicker/bootstrap-datepicker.js"></script>
    <script src="~/Scripts/js/plugins/chosen/chosen.jquery.js"></script>
    <script src="~/Scripts/js/plugins/iCheck/icheck.min.js"></script>

    <script type="text/javascript" language="javascript">
    $(document).ready(function() {

        window.upsert = function(id) {
            window.showUpsert(id, "#angJsjqGridId", "@Url.Action("Upsert", "Client")", "#GridId");
        };

        window.licenseManagement = function(id) {
            var params= {};
            params.idParam=id;
            window.goToUrlMvcUrl('@Url.Action("Index", "License")?clId=idParam', params);
        };

        jQuery("#GridId").jqGrid({
            url: '@Url.Action("List", "Client")',
            datatype: "json",
            mtype: 'POST',
            colNames: ['ID', 'Cliente', 'Compañía', 'Correo electrónico', 'Teléfono', 'Dirección', 'País', 'Acci&oacute;n'],
            colModel: [
                { name: 'ClientId', index: 'ClientId', hidden: true },
                { name: 'FullName', index: 'FullName', width: 310, align: "center", sorttype: 'string', searchoptions: { sopt: ['bw'] } },
                { name: 'Company', index: 'Company', width: 200, align: "center", sorttype: 'string', search: false },
                { name: 'Email', index: 'Email', width: 200, align: "center", sorttype: 'string', search: false },
                { name: 'Phone', index: 'Phone', width: 140, align: "center", sorttype: 'string', search: false },
                { name: 'FullAddress', index: 'FullAddress', width: 250, align: "center", sorttype: 'string', search: false },
                { name: 'CountryName', index: 'CountryName', width: 110, align: "center", sorttype: 'string', search: false },
                { name: 'Action', width: 110, align: "center", sortable: false, search: false, formatter: window.actionFormatter }
            ],
            rowNum: 10,
            rowList: [10, 30, 50],
            pager: '#GridPager',
            sortname: 'ClientId',
            height: 450,
            viewrecords: true,
            autowidth: true,
            shrinkToFit: true,
            sortorder: "desc",
            caption: "",
            add: true,
            edit: true,
            addtext: 'Agregar',
            edittext: 'Editar',
            altRows: true,
            hidegrid: false,
            gridComplete: function() {
                var ids = $(this).jqGrid('getDataIDs');
                for (var i = 0; i < ids.length; i++) {
                    var cl = ids[i];
                    var be = "";

                    be += "<a href=\"javascript:;\" style=\"display:inline-block;\" title=\"Editar cliente\" onclick=\"window.upsert('" + cl + "');\"><i class=\"fa fa-pencil icon-grid-st blue-light\"></i></a>&nbsp;&nbsp;";
                    be += "<a href=\"javascript:;\" style=\"display:inline-block;\" title=\"Administrar licencias del cliente\" onclick=\"window.licenseManagement('" + cl + "');\"><i class=\"fa fa-key icon-grid-st red\"></i></a>&nbsp;&nbsp;";
                    //be += "<a href=\"javascript:;\" style=\"display:inline-block;\" title=\"Descargar código de activación\" onclick=\"window.downloadCode('" + cl + "');\"><i class=\"fa fa-cloud-download icon-grid-st blue-light\"></i></a>  ";
                    //be += "<a href=\"javascript:;\" style=\"display:inline-block;\" title=\"Enviar por correo electrónico el código de activación\" onclick=\"window.sendEmail('" + cl + "');\"><i class=\"fa fa-envelope icon-grid-st orange\"></i></a>  ";
                    //be += "<a href=\"javascript:;\" style=\"display:inline-block;\" title=\"Eliminar licencia\" onclick=\"window.obsolete('" + cl + "');\"><i class=\"fa fa-trash icon-grid-st red\"></i></a>";

                    $(this).jqGrid('setRowData', ids[i], { Action: be });
                }
            }
        });

        jQuery("#GridId").jqGrid('navGrid', '#GridPager', {
            edit: false,
            add: true,
            addfunc: window.upsert,
            refresh: true,
            del: false,
            search: false
        });

        jQuery("#GridId").jqGrid('filterToolbar', {
            stringResult: true,
            searchOperators: true,
            searchOnEnter: true,
            multipleSearch: true,
            ignoreCase: true
        });

        $(window).bind('resize', function() {
            var width = $('.jqGrid_wrapper').width();
            $('#GridId').setGridWidth(width);
        });
    });
    </script>
}